### PR TITLE
Fix scheduler issues of sync puts/forks/takes

### LINKED ISSUE #413: Forked tasks can't always take actions from its siblings
Original Reference: https://github.com/yelouafi/redux-saga/issues/277#issuecomment-228443152

I would expect this code to work as-is.

``` js
export default function * rootSaga () {
  yield fork(watchPing)
  yield put({type: 'PING', val: 0})
}

function * watchPing () {
  yield * takeEvery('PING', ackWorker)
  // yield * fixedTakeEvery('PING', ackWorker)
}

let first = true

function * ackWorker (action) {
  // yield Promise.resolve()
  if (first) {
    first = false
    yield put({type: 'PING', val: action.val + 1})
    yield take(`ACK-${action.val + 1}`)
  }
  yield put({type: `ACK-${action.val}`})
}

export function * fixedTakeEvery (actionType, saga) {
  const worker = function * (...args) {
    yield Promise.resolve()
    yield fork(saga, ...args)
  }
  yield * takeEvery(actionType, worker)
}
```

The above code results in PING, PING, ACK-1. But if you uncomment the yield Promise.resolve() or switch from takeEvery() to fixedTakeEvery() you will get the full sequence of PING, PING, ACK-1, ACK-0.

I tried to put this into an actual test case, but I'm getting different behavior (although the test is still failing).

``` js
test('inter-saga fork/take back from forked child 3', assert => {
  assert.plan(1);

  const actual = []
  const chan = channel()

  const middleware = sagaMiddleware()
  const store = createStore(() => {}, applyMiddleware(middleware))

  let first = true

  function* root() {
    yield [fork(watchPing)]
  }

  function* watchPing () {
    yield * takeEvery('PING', ackWorker)
    // yield * fixedTakeEvery('PING', ackWorker)
  }

  function* ackWorker (action) {
    // yield Promise.resolve()
    if (first) {
      first = false
      yield put({type: 'PING', val: action.val + 1})
      yield take(`ACK-${action.val + 1}`)
    }
    yield put({type: `ACK-${action.val}`})
    actual.push(1)
  }

  function* fixedTakeEvery (actionType, saga) {
    const worker = function * (...args) {
      yield Promise.resolve()
      yield fork(saga, ...args)
    }
    yield * takeEvery(actionType, worker)
  }


  middleware.run(root).done.then(() => {
    assert.deepEqual(actual, [1,1],
      "Sagas must take actions from each forked childs doing Sync puts"
    );
    assert.end();
  })

  store.dispatch({type: 'PING', val: 0})
  store.dispatch(END)
});
```

In the test case actual ends up with just `[1]` which is expected. But I would expect that uncommenting the `yield Promise.resolve()` would give `[1,0]`, but instead it gives `[]`.

### PR DESCRIPTION
**Pull request by yelouafi**
Replace the previous lock based scheduler with a new one based on [semaphores](https://en.wikipedia.org/wiki/Semaphore_(programming)) (to handle nested schedules). 

Fixes #413 and #598 (via test case provided in #602)

### CODE REVIEW

File: src/internal/asap.js [hunk 1]
```diff
@@ -1,21 +1,31 @@
...
+}
+
 asap.flush = () => {
-  let nextTask
-  while((nextTask = queue.shift())) {
+  //console.log('flush start')
+  semaphore--
+  while(!semaphore && queue.length) {
+    const nextTask = queue.shift()
+    semaphore++
```
Comment (Andarist) [inline src/internal/asap.js]: wondering if `asap.suspend()` shouldnt be used here for consistency, but then `semaphore--` maybe should get its own function, with more descriptive name, smth like - `asap.lift()`

**Comment by Andarist** [comment]
Wow this is more than cool! 🎉 Superb important for the lib and handled gracefully! Just dont forget to erase those commented out `// console.log`s ;) Should I close PR#602?

cc @mjrussell

**Comment by mjrussell** [comment]
👏 nicely done!

File: src/internal/asap.js (hunk 1 above)
Comment (yelouafi) [inline src/internal/asap.js]: did some refactorings

**Comment by yelouafi** [comment]
>Should I close PR #602 ?

Yes the test is already included in this PR (thanks to it the #598 case was greatly simplified)

File: src/internal/proc.js [hunk 2]
```diff
@@ -487,22 +486,30 @@ export default function proc(
   function runForkEffect({context, fn, args, detached}, effectId, cb) {
     const taskIterator = createTaskIterator({context, fn, args})
 
-    asap.suspend()
-    const task = proc(taskIterator, subscribe, dispatch, getState, options, effectId, fn.name, (detached ? null : noop))
+    try {
+      /**
+        put the scheduler in the `suspended` state
+        this will prevent nested puts from perfoming until this Saga is ready to take them
```
Comment (Andarist) [inline src/internal/proc.js]: perfo*r*ming

File: src/internal/proc.js [hunk 3]
```diff
@@ -487,22 +486,30 @@ export default function proc(
   function runForkEffect({context, fn, args, detached}, effectId, cb) {
     const taskIterator = createTaskIterator({context, fn, args})
 
-    asap.suspend()
-    const task = proc(taskIterator, subscribe, dispatch, getState, options, effectId, fn.name, (detached ? null : noop))
+    try {
```
Comment (Andarist) [inline src/internal/proc.js]: I see there is a new `try` here, but without corresponding `catch`, shouldnt something be done with the `error`? Also - what is it guarding from? `fn` throwing? 

this simple `try` can swallow errors easily and make debugging a nightmare

File: src/internal/scheduler.js [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+let semaphore = 0
+
+/**
+  Executes a task 'atomically'. Tasks scheduled during this execution will be queued
+  and flushed after this task has finished (assuming the scheduler endup in a released
+  state).
+**/
+function exec(task) {
+  try {
+    suspend()
```
Comment (Andarist) [inline src/internal/scheduler.js]: same comment goes here for `try` without `catch` block

File: src/internal/proc.js (hunk 3 above)
Comment (yelouafi) [inline src/internal/proc.js]: try/finally wont swallow errors since there is no swallowing catch. It simply ensures that the scheduler is always in a consistent state; every suspend must have a corresponding flush.

File: src/internal/proc.js [hunk 5]
```diff
@@ -428,12 +428,11 @@ export default function proc(
   }
 
   function runPutEffect({channel, action, sync}, cb) {
-    /*
-      Use a reentrant lock `asap` to flatten all nested dispatches
-      If this put cause another Saga to take this action an then immediately
-      put an action that will be taken by this Saga. Then the outer Saga will miss
-      the action from the inner Saga b/c this put has not yet returned.
-    */
+    /**
```
Comment (yelouafi) [inline src/internal/proc.js]: yes I think it's redundant

File: src/internal/asap.js (hunk 1 above)
Comment (Andarist) [inline src/internal/asap.js]: really nice job with that refactor, `scheduler` got much clearer now

**Comment by Andarist** [comment]
No much to do here more if all tests are passing, merge at asap! (pun intended ;) )
